[workspace]
members = ["subscriber", "publisher"]

[workspace.dependencies]
nostr-sdk = "0.40.0"  
nostr = "0.40.0"
tokio = { version = "1.44.1", features = ["full"] }
solana-sdk = "2.2.2"
solana-client = "2.2.6" 
serde = "1.0.219"
serde_json = "1.0.140"